user_new:
    path: /new
    defaults: { _controller: AppBundle:User:new }
    

user_edit:
    path: /edit
    defaults: { _controller: AppBundle:User:edit }
    methods: POST
    
user_upload_Image:
    path: /upload-image-user
    defaults: { _controller: AppBundle:User:uploadImage }
    methods: POST
    