<?php

namespace BDBundle\Entity;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUsers() {
        $em = $this->getEntityManager();
        $dql = 'Select u
                from BDBundle:Users u
               ';
        $query = $em->createQuery($dql);
        $users= $query->getArrayResult();
        return $users;
    }
}
