<?php

namespace BDBundle\Entity;

/**
 * VideosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideosRepository extends \Doctrine\ORM\EntityRepository
{
}
